version: "3.9"

services: 
    db:
            # container_name: postgresql
        image: postgres:13
        ports:
          - "5432:5432" # 1. 컨테이너와 호스트가 각각 5432포트로 통신
        restart: always # 2. 컨테이너가 종료되면 항상 재시작 
        environment: # 3. 환경변수 3가지 설정
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        volumes:
                - pgdata:/var/lib/postgresql/data # 4. /var/lib/postgresql/data를 pgdata 볼륨으로 할당 
        

    
    pgadmin:
            # container_name: pgadmin
        image: dpage/pgadmin4
        logging:
            driver: none
        ports:
          - "5050:80" #1. 컨테이너의 5050포트와 호스트의 80포트 연결 
        restart: always # 2. 컨테이너가 종료되면 항상 재시작
        environment: # 3. 환경변수 2가지 설정
          - PGADMIN_DEFAULT_EMAIL=admin@example.com
          - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
                - pgadmindata:/var/lib/pgadmin # 4. /var/lib/pgadmin를 pgadmindata 볼륨으로 할당 

    web:
            # container_name: fastapi
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        volumes: 
          - .:/code
        build: . # 1. Dockerfile을 빌드한 이미지 사용 
        ports: 
          - "8000:8000" # 2. 컨테이너와 호스트는 각각 8000번 포트로 통신
        depends_on:
          - db # 3. postgreSQL(db) 서비스가 시작된 이후에 시작
        restart: always # 4. 컨테이너가 종료되면 항상 재시작 

volumes: 
  pgdata:
  pgadmindata:
